-- CreateEnum
CREATE TYPE "PostStatus" AS ENUM ('DRAFT', 'PUBLISHED', 'ARCHIVED');

-- DropIndex
DROP INDEX "Post_category_idx";

-- DropIndex
DROP INDEX "Post_publishedAt_idx";

-- DropIndex
DROP INDEX "Post_visibility_idx";

-- AlterTable: add nullable columns first (status added as nullable for backfill)
ALTER TABLE "Post"
  ADD COLUMN "firstPublishedAt" TIMESTAMP(3),
  ADD COLUMN "archivedAt" TIMESTAMP(3),
  ADD COLUMN "deletedAt" TIMESTAMP(3),
  ADD COLUMN "publishedById" TEXT,
  ADD COLUMN "archivedById" TEXT,
  ADD COLUMN "deletedById" TEXT,
  ADD COLUMN "status" "PostStatus";

-- Backfill: classify existing rows based on publishedAt
UPDATE "Post"
SET
  "status" = CASE
    WHEN "publishedAt" IS NOT NULL THEN 'PUBLISHED'::"PostStatus"
    ELSE 'DRAFT'::"PostStatus"
  END,
  "firstPublishedAt" = CASE
    WHEN "publishedAt" IS NOT NULL THEN "publishedAt"
    ELSE NULL
  END;

-- Now make status NOT NULL with default
ALTER TABLE "Post"
  ALTER COLUMN "status" SET NOT NULL,
  ALTER COLUMN "status" SET DEFAULT 'DRAFT';

-- Update author FK to ON DELETE RESTRICT
-- Drop the existing FK, then recreate it with Restrict
ALTER TABLE "Post" DROP CONSTRAINT IF EXISTS "Post_authorId_fkey";

ALTER TABLE "Post"
  ADD CONSTRAINT "Post_authorId_fkey"
  FOREIGN KEY ("authorId")
  REFERENCES "User"("id")
  ON DELETE RESTRICT
  ON UPDATE CASCADE;

-- Add FK for auditor fields
ALTER TABLE "Post"
  ADD CONSTRAINT "Post_publishedById_fkey"
  FOREIGN KEY ("publishedById")
  REFERENCES "User"("id")
  ON DELETE SET NULL
  ON UPDATE CASCADE;

ALTER TABLE "Post"
  ADD CONSTRAINT "Post_archivedById_fkey"
  FOREIGN KEY ("archivedById")
  REFERENCES "User"("id")
  ON DELETE SET NULL
  ON UPDATE CASCADE;

ALTER TABLE "Post"
  ADD CONSTRAINT "Post_deletedById_fkey"
  FOREIGN KEY ("deletedById")
  REFERENCES "User"("id")
  ON DELETE SET NULL
  ON UPDATE CASCADE;

-- CHECK constraint: status × dates consistency
ALTER TABLE "Post"
  ADD CONSTRAINT "chk_post_status_dates"
  CHECK (
    ("status" = 'DRAFT'::"PostStatus"
      AND "firstPublishedAt" IS NULL
      AND "publishedAt" IS NULL
      AND "archivedAt" IS NULL)
    OR
    ("status" = 'PUBLISHED'::"PostStatus"
      AND "firstPublishedAt" IS NOT NULL
      AND "publishedAt" IS NOT NULL
      AND "archivedAt" IS NULL)
    OR
    ("status" = 'ARCHIVED'::"PostStatus"
      AND "firstPublishedAt" IS NOT NULL
      AND "publishedAt" IS NOT NULL
      AND "archivedAt" IS NOT NULL)
  );

-- Partial index: feed de posts ativos (PUBLISHED, não deletados)
CREATE INDEX "Post_feed_active_idx"
  ON "Post" ("status", "visibility", "publishedAt" DESC, "id" DESC)
  WHERE "deletedAt" IS NULL;

-- Partial index: gestão editorial por autor
CREATE INDEX "Post_author_management_idx"
  ON "Post" ("authorId", "status", "updatedAt" DESC, "id" DESC)
  WHERE "deletedAt" IS NULL;

-- Drop the generic compound index generated by Prisma (we use partial indexes instead)
DROP INDEX IF EXISTS "Post_authorId_status_updatedAt_id_idx";
